### ISSUE TITLE
Building Mod Suggestion

### ISSUE THREAD

**Issue by Miirik** [MindBrain27/Kitchen-Cauldron#31]
I've been loving the modpack so far, but was wondering if you could consider adding another building mod to flesh out options for builders a bit more alongside mods already there. 

The most quality ones my server has played with in the past are: https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture and https://www.curseforge.com/minecraft/mc-mods/another-furniture but if they don't fit your vision of the pack, that's totally cool!

**Comment by MindBrain27** [comment]
I'll definitely look into them, I am in no way considered a builder so I imagine there's quite a bit of builders tools missing. Feel free to leave any other suggestions here.

**Comment by MindBrain27** [comment]
Added both, I absolutely love Fantasy's Furniture, thankyou. Update will be this weekend.

**Comment by MindBrain27** [comment]
added in newest update
